function [tau_s, AD, AD_err, f, srPSD, srPSD_err, f_full, srPSD_full,...
    tau_range, f_range,...
    noise_term_vals, noise_term_errs, ...
    allan_noise_term_vals, allan_noise_term_errs, ...
    srPSD_noise_term_vals, srPSD_noise_term_errs] = ...
    get_noise_spectrum_and_parameters(Omega_deg_hr, fs, bw_est, force_keep_terms, downsample_and_filter_psd)

% This function calls the function calculating the Allan deviation and PSD, 
% and the one fitting the two curves to extract noise models.
% See documentation of the two daughter functions for details.

if ~exist('bw_est','var') || isempty(bw_est)
    bw_est = 90;
end
if ~exist('force_keep_terms','var') || isempty(force_keep_terms)
    force_keep_terms = [];
end
if ~exist('downsample_and_filter_psd','var') || isempty(downsample_and_filter_psd)
    downsample_and_filter_psd = 1;
end

warning('off')

[tau_s, AD, AD_err, f, srPSD, srPSD_err, f_full, srPSD_full] = ...
    get_allan_and_psd_from_data(Omega_deg_hr, fs, [], ...
    struct('downsample_and_filter',downsample_and_filter_psd,'method','ieee-log'));

[tau_range, f_range,...
    noise_term_vals, noise_term_errs, ...
    allan_noise_term_vals, allan_noise_term_errs, ...
    srPSD_noise_term_vals, srPSD_noise_term_errs] = ...
    get_noise_parameters(tau_s, AD, AD_err, f, srPSD, srPSD_err, ...
    bw_est, force_keep_terms);

warning('on')