%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ASAFMAN\Dropbox\MiniMe\minime_operational\scope_5.csv
%
% Auto-generated by MATLAB on 29-Nov-2022 10:42:24

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["xaxis", "VarName2", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["xaxis", "VarName2"];
opts.VariableTypes = ["double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
scope5 = readtable("C:\Users\ASAFMAN\Dropbox\MiniMe\minime_operational\scope_4.csv", opts);

%% Convert to output type
scope5 = table2array(scope5);

%% Clear temporary variables
clear opts

figure;
plot(scope5(:,1),scope5(:,2))
Fs = 1/(scope5(2,1)-scope5(1,1))
