function [allan_fit] = fit_allan(tau, allan)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

%% fit a Allen
fit_op = fitoptions('Method','NonlinearLeastSquares',...
                    'Lower',[0, 0, 0],...
                    'Upper',[Inf, Inf, Inf],...
                    'StartPoint',[1e5, 1e4, 1e2]);

noise_model = fittype('(h2/(x^2)) + (h0/x) + (hm1)', ...
                      'coefficients', {'h2', 'h0', 'hm1',}, ...
                      'options', fit_op);

allan_fit = fit(tau', allan', noise_model);


% % second try fit
fit_op = fitoptions('Method','NonlinearLeastSquares',...
                    'Lower',[0, 0, 0],...
                    'Upper',[Inf, Inf, Inf],...
                    'StartPoint',[allan_fit.h2, allan_fit.h0, ...
                    allan_fit.hm1]);
                
noise_model = fittype('(h2/(x^2)) + (h0/x) + (hm1)', ...
                      'coefficients', {'h2', 'h0', 'hm1',}, ...
                      'options', fit_op);

                
allan_fit = fit(tau', allan', noise_model);


% %% fit a Allen
% fit_op = fitoptions('Method','NonlinearLeastSquares',...
%                     'Lower',[0, 0, 0],...
%                     'Upper',[Inf, Inf, Inf],...
%                     'StartPoint',[1e5, 1e4, 1e2]);
% 
% noise_model = fittype('(h2/(x)) + (h0/sqrt(x)) + (hm1)', ...
%                       'coefficients', {'h2', 'h0', 'hm1',}, ...
%                       'options', fit_op);
% 
% allan_fit = fit(tau', allan', noise_model);
% 
% 
% % % second try fit
% fit_op = fitoptions('Method','NonlinearLeastSquares',...
%                     'Lower',[0, 0, 0],...
%                     'Upper',[Inf, Inf, Inf],...
%                     'StartPoint',[allan_fit.h2, allan_fit.h0, ...
%                     allan_fit.hm1]);
%                 
% noise_model = fittype('(h2/(x)) + (h0/sqrt(x)) + (hm1)', ...
%                       'coefficients', {'h2', 'h0', 'hm1',}, ...
%                       'options', fit_op);
% 
%                 
% allan_fit = fit(tau', allan', noise_model);


end

